services:
  api:
    container_name: "wine-region-evaluator-api"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py seed_regions && python manage.py test && python manage.py runserver 0.0.0.0:8000"

  db:
    container_name: postgres_db
    image: postgres:14
    environment:
      TZ: UTC
      PGT: UTC
    env_file:
      - .env
    volumes:
    - database_volume:/var/lib/postgresql/data
    expose:
      - 5432

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    expose:
      - 6379
      
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config beat
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery

volumes:
  database_volume: {}