# Generated by Django 5.1.6 on 2025-03-06 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mean_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
                ('min_temperature', models.FloatField()),
                ('min_humidity', models.FloatField()),
                ('max_humidity', models.FloatField()),
                ('mean_humidity', models.FloatField()),
                ('rain', models.FloatField()),
                ('cloud_cover', models.FloatField()),
                ('soil_moisture', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.location')),
            ],
        ),
    ]
