# Generated by Django 5.1.6 on 2025-03-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_climatereading'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='climatereading',
            unique_together={('location', 'date')},
        ),
        migrations.AddIndex(
            model_name='climatereading',
            index=models.Index(fields=['location', 'date'], name='main_climat_locatio_0be317_idx'),
        ),
    ]
