# Generated by Django 5.1.6 on 2025-03-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_climatereading_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('latitude', 'longitude')},
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitude', 'longitude'], name='main_locati_latitud_908845_idx'),
        ),
    ]
