# Generated by Django 5.1.6 on 2025-03-06 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_location_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatereading',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_readings', to='main.location'),
        ),
    ]
