# Generated by Django 5.1.6 on 2025-03-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_climatereading_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Region',
        ),
        migrations.RemoveIndex(
            model_name='climatereading',
            name='main_climat_locatio_0be317_idx',
        ),
        migrations.RenameField(
            model_name='climatereading',
            old_name='location',
            new_name='region',
        ),
        migrations.RenameIndex(
            model_name='region',
            new_name='main_region_latitud_db5627_idx',
            old_name='main_locati_latitud_908845_idx',
        ),
        migrations.AlterUniqueTogether(
            name='climatereading',
            unique_together={('region', 'date')},
        ),
        migrations.AddIndex(
            model_name='climatereading',
            index=models.Index(fields=['region', 'date'], name='main_climat_region__8c754a_idx'),
        ),
    ]
